id: liber-objectum-seanron-mccarter
title: "Liber Objectum"
author: Sean 'Seanron' McCarter
version: 5.0.0
license: GPL-3.0-only

replaces: []

requires: []

descriptive_tags: [mission-pack, deployment-maps, expansion-missions, legendary-missions, matched-play]

files:
  - Liber Objectum.pdf
